### GET ALL BOOKINGS
###
POST http://localhost:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query {
  bookings {
    _id
    createdAt
    updatedAt
    event {
      title
      description
      price
    }
    user {
      email
    }
  }
}

### BOOK THE EVENT
###
POST http://localhost:4000/graphql HTTP/1.1
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation ($event: ID!, $user: ID!) {
  bookEvent(event: $event, user: $user) {
    _id
    createdAt
    updatedAt
  }
}

{
  "event": "64c4e1e9afab567ad0281288",
  "user": "64beb21c383b7d285d1339e7"
}

### CANCEL THE BOOKING
###
POST http://localhost:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

mutation ($_id: ID!) {
  cancelBooking(_id: $_id) {
    _id
    title
    description
    creator {
      email
    }
  }
}

{
  "_id": "64c504819f9fe61b6ae50118"
}