### GET ALL EVENTS
###
POST http://localhost:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZGFybWlhbkBleGFtcGxlLmNvbSIsImlhdCI6MTY5MDc0MTU2OSwiZXhwIjoxNjkwNzQxNjI5fQ.VJr4iznG4WmNg6xRmOjeisPyU6EPdT6bCYknsux3GHw

query {
  events {
    _id
    title
    description
    price
    date
    creator {
      _id
      email
    }
  }
}

### GET EVENT BY ID
###
POST http://localhost:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZGFybWlhbkBleGFtcGxlLmNvbSIsImlhdCI6MTY5MDc0Mjk0MCwiZXhwIjoxNjkwNzQzNTQwfQ.eAi6PNyygMAVFrrLWi7hAyGf7rqeo7xtOG0SFm8b4kg

query ($_id: ID!) {
  event(_id: $_id) {
    _id
    title
    description
    price
    date
    creator {
      _id
      email
    }
  }
}

{
  "_id": "64c3caf57d88383cc432fac4"
}

### CREATE EVENT
###
POST http://localhost:4000/graphql HTTP/1.1
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZGFybWlhbkBleGFtcGxlLmNvbSIsImlhdCI6MTY5MDc0MTU2OSwiZXhwIjoxNjkwNzQxNjI5fQ.VJr4iznG4WmNg6xRmOjeisPyU6EPdT6bCYknsux3GHw

mutation ($event: AddEventInput!) {
  addEvent(event: $event) {
    _id
    title
    description
    price
    date 
  }
}

{
  "event": {
    "title": "Visit Ataturk House",
    "description": "New desc 2",
    "price": 59.99,
    "date": "2023-07-23T05:14:27.979Z",
    "creator": "64c63101ba2efef9b597e9a7"
  }
}

### UPDATE THE EVENT
###
POST http://localhost:4000/graphql HTTP/1.1
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZGFybWlhbkBleGFtcGxlLmNvbSIsImlhdCI6MTY5MDc0MTU2OSwiZXhwIjoxNjkwNzQxNjI5fQ.VJr4iznG4WmNg6xRmOjeisPyU6EPdT6bCYknsux3GHw

mutation ($_id: ID!, $edits: UpdateEventInput!) {
  updateEvent(_id: $_id, edits: $edits) {
    _id
    title
    description
    price
    date 
  }
}

{
  "_id": "64c673e080f625553ba6b5b4",
  "edits": {
    "title": "Visit Ataturk's house",
    "description": "New desc 3"
  }
}

### DELETE THE EVENT
###
POST http://localhost:4000/graphql HTTP/1.1
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZGFybWlhbkBleGFtcGxlLmNvbSIsImlhdCI6MTY5MDc0MTU2OSwiZXhwIjoxNjkwNzQxNjI5fQ.VJr4iznG4WmNg6xRmOjeisPyU6EPdT6bCYknsux3GHw

mutation ($_id: ID!) {
  deleteEvent(_id: $_id) {
    _id
    title
    description
    price
    date 
  }
}

{
  "_id": "64c4e1e9afab567ad0281288"
}