###
POST http://localhost:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhcm1pYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE2OTA5MDA1MDgsImV4cCI6MTY5MDkwMTEwOH0.QPTt4VxUK6CEwaPThV0jNwyjfOC4OGSoXP1kUPiUyoQ

query {
  users{
    _id
    email
    createdEvents {
      _id
      title
      description
      date
    }
  }
}

###
POST http://localhost:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhcm1pYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE2OTA5MDA1MDgsImV4cCI6MTY5MDkwMTEwOH0.QPTt4VxUK6CEwaPThV0jNwyjfOC4OGSoXP1kUPiUyoQ

query ($_id: ID!) {
  user(_id: $_id) {
    _id
    email
    createdEvents {
      title
      description
      date
    }
  }
}

{
  "_id": "64c63101ba2efef9b597e9a7"
}