###
POST http://localhost:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhcm1pYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE2OTA4Mjk1MTUsImV4cCI6MTY5MDgzMDExNX0.petLH5uuNC65RJ9-oDOKgFoFQpZ_HjZDBw_aAh1Zbkg

query {
  users{
    _id
    email
    createdEvents {
      _id
      title
      description
      date
    }
  }
}

###
POST http://localhost:4000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhcm1pYW5AZXhhbXBsZS5jb20iLCJpYXQiOjE2OTA4Mjk1MTUsImV4cCI6MTY5MDgzMDExNX0.petLH5uuNC65RJ9-oDOKgFoFQpZ_HjZDBw_aAh1Zbkg

query ($_id: ID!) {
  user(_id: $_id) {
    _id
    email
    createdEvents {
      title
      description
      date
    }
  }
}

{
  "_id": "64c63101ba2efef9b597e9a7"
}